In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
#preprocess data
#remove irrelevant data
data=data.drop(['RowNumber','CustomerId','Surname'], axis=1)

In [4]:
#encode categorical variable
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
#one hot encode geography
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first')
geo_encoded=ohe.fit_transform(data[['Geography']])
geo_encoded=geo_encoded.toarray()

In [7]:
geo_df= pd.DataFrame(
  geo_encoded,
  columns=ohe.get_feature_names_out(['Geography'])

)
data=pd.concat([data, geo_df],axis=1)

In [8]:
data=data.drop(['Geography'], axis=1)

In [9]:
#divide data into independent and dependent data

X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [10]:
#split train test
X_train,X_test,y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [12]:
#save encoders and scalers
with open('label_encoder_gender.pkl','wb') as file:
  pickle.dump(label_encoder_gender, file)

with open('ohe.pkl', 'wb') as file:
  pickle.dump(ohe, file)

with open('scaler.pkl', 'wb') as file:
  pickle.dump(scaler, file)

## ANN Regression

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

WARNING:tensorflow:From d:\conda_envs\DL1\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [14]:
#build ANN model
model=Sequential([
  Dense(64, activation='relu', input_shape=(X_train.shape[1],)), #first hidden layer connected with input layer
  Dense(32, activation='relu'),#hidden layer 2
  Dense(1)#output layer
]

)

WARNING:tensorflow:From d:\conda_envs\DL1\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [15]:
model.compile(optimizer='adam',loss='mean_absolute_error', metrics=['mae'])

model.summary()

WARNING:tensorflow:From d:\conda_envs\DL1\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                768

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2881 (11.25 KB)
Trainable params: 2881 (11.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [16]:
#set up tensor board
import datetime
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir="regressionlogs/fit"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [17]:
## set up early stopping where loss not decreasing anymore
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [18]:
#training the model
history=model.fit(
  X_train, y_train, validation_data=(X_test, y_test), epochs=100,
  callbacks=[tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From d:\conda_envs\DL1\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\conda_envs\DL1\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 1s 3ms/step - loss: 100377.0781 - mae: 100377.0781 - val_loss: 98521.5781 - val_mae: 98521.5781
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 99660.4766 - mae: 99660.4766 - val_loss: 97088.1875 - val_mae: 97088.1875
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 97170.7422 - mae: 97170.7422 - val_loss: 93456.5938 - val_mae: 93456.5938
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 92300.3359 - mae: 92300.3359 - val_loss: 87403.1016 - val_mae: 87403.1016
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 85200.9922 - mae: 85200.9922 - val_loss: 79515.9219 - val_mae: 79515.9219
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 76686.2344 - mae: 76686.2344 - val_loss: 71009.2500 - val_mae: 71009.2500
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 68295.0938 - mae: 68295.0938 - val_loss: 63471.3945 - val_mae: 63471.3945
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 61264.5781 - mae: 61264.5781 - val_loss: 57630.3633 - val_mae: 57630.3633
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 56258.2305 - mae: 56258.2305 - val_loss: 53894.8008 - val_mae: 53894.8008
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 53299.7969 - mae: 53299.7969 - val_loss: 52019.8633 - val_mae: 52019.8633
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 51780.6523 - mae: 51780.6523 - val_loss: 51238.0664 - val_mae: 51238.0664
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 51099.2188 - mae: 51099.2188 - val_loss: 50965.2695 - val_mae: 50965.2695
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 50802.0625 - mae: 50802.0625 - val_loss: 50833.2812 - val_mae: 50833.2812
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 50634.9297 - mae: 50634.9297 - val_loss: 50740.4727 - val_mae: 50740.4727
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 50525.0781 - mae: 50525.0781 - val_loss: 50693.7266 - val_mae: 50693.7266
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 50443.1680 - mae: 50443.1680 - val_loss: 50642.5273 - val_mae: 50642.5273
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 50371.8047 - mae: 50371.8047 - val_loss: 50604.4219 - val_mae: 50604.4219
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 50307.8203 - mae: 50307.8203 - val_loss: 50567.3398 - val_mae: 50567.3398
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 50252.4648 - mae: 50252.4648 - val_loss: 50529.0625 - val_mae: 50529.0625
Epoch 20/100
250/250 [==============================] - 1s 2ms/step - loss: 50204.6406 - mae: 50204.6406 - val_loss: 50510.8516 - val_mae: 50510.8516
Epoch 21/100
250/250 [==============================] - 0s 2ms/step - loss: 50157.5391 - mae: 50157.5391 - val_loss: 50477.9258 - val_mae: 50477.9258
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 50117.6055 - mae: 50117.6055 - val_loss: 50461.1289 - val_mae: 50461.1289
Epoch 23/100
250/250 [==============================] - 0s 2ms/step - loss: 50081.1289 - mae: 50081.1289 - val_loss: 50439.5898 - val_mae: 50439.5898
Epoch 24/100
250/250 [==============================] - 0s 2ms/step - loss: 50045.7383 - mae: 50045.7383 - val_loss: 50409.0234 - val_mae: 50409.0234
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 50010.5703 - mae: 50010.5703 - val_loss: 50395.3945 - val_mae: 50395.3945
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 49980.9023 - mae: 49980.9023 - val_loss: 50376.6992 - val_mae: 50376.6992
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 49954.6172 - mae: 49954.6172 - val_loss: 50370.5664 - val_mae: 50370.5664
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 49927.7188 - mae: 49927.7188 - val_loss: 50353.5703 - val_mae: 50353.5703
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 49902.8086 - mae: 49902.8086 - val_loss: 50332.6016 - val_mae: 50332.6016
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 49879.3516 - mae: 49879.3516 - val_loss: 50311.1680 - val_mae: 50311.1680
Epoch 31/100
250/250 [==============================] - 1s 2ms/step - loss: 49857.5742 - mae: 49857.5742 - val_loss: 50307.9297 - val_mae: 50307.9297
Epoch 32/100
250/250 [==============================] - 0s 2ms/step - loss: 49838.1914 - mae: 49838.1914 - val_loss: 50314.6680 - val_mae: 50314.6680
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 49817.9609 - mae: 49817.9609 - val_loss: 50310.3945 - val_mae: 50310.3945
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 49803.3906 - mae: 49803.3906 - val_loss: 50288.1758 - val_mae: 50288.1758
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 49788.2109 - mae: 49788.2109 - val_loss: 50276.6758 - val_mae: 50276.6758
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 49770.8906 - mae: 49770.8906 - val_loss: 50275.0781 - val_mae: 50275.0781
Epoch 37/100
250/250 [==============================] - 1s 2ms/step - loss: 49757.3945 - mae: 49757.3945 - val_loss: 50263.9492 - val_mae: 50263.9492
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 49744.9531 - mae: 49744.9531 - val_loss: 50266.6680 - val_mae: 50266.6680
Epoch 39/100
250/250 [==============================] - 0s 2ms/step - loss: 49730.0156 - mae: 49730.0156 - val_loss: 50247.1797 - val_mae: 50247.1797
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 49715.6914 - mae: 49715.6914 - val_loss: 50256.7422 - val_mae: 50256.7422
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 49704.9570 - mae: 49704.9570 - val_loss: 50250.5000 - val_mae: 50250.5000
Epoch 42/100
250/250 [==============================] - 0s 2ms/step - loss: 49692.6289 - mae: 49692.6289 - val_loss: 50243.4570 - val_mae: 50243.4570
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 49681.7383 - mae: 49681.7383 - val_loss: 50233.8086 - val_mae: 50233.8086
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 49665.7656 - mae: 49665.7656 - val_loss: 50233.8438 - val_mae: 50233.8438
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 49659.9727 - mae: 49659.9727 - val_loss: 50246.6328 - val_mae: 50246.6328
Epoch 46/100
250/250 [==============================] - 0s 2ms/step - loss: 49647.4102 - mae: 49647.4102 - val_loss: 50229.6641 - val_mae: 50229.6641
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 49634.8984 - mae: 49634.8984 - val_loss: 50216.3828 - val_mae: 50216.3828
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49625.6797 - mae: 49625.6797 - val_loss: 50212.7617 - val_mae: 50212.7617
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 49618.5508 - mae: 49618.5508 - val_loss: 50210.3438 - val_mae: 50210.3438
Epoch 50/100
250/250 [==============================] - 0s 2ms/step - loss: 49607.4648 - mae: 49607.4648 - val_loss: 50209.1211 - val_mae: 50209.1211
Epoch 51/100
250/250 [==============================] - 0s 2ms/step - loss: 49598.6836 - mae: 49598.6836 - val_loss: 50201.3203 - val_mae: 50201.3203
Epoch 52/100
250/250 [==============================] - 1s 2ms/step - loss: 49591.5625 - mae: 49591.5625 - val_loss: 50203.9102 - val_mae: 50203.9102
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 49582.8047 - mae: 49582.8047 - val_loss: 50194.9609 - val_mae: 50194.9609
Epoch 54/100
250/250 [==============================] - 0s 2ms/step - loss: 49571.8633 - mae: 49571.8633 - val_loss: 50201.6836 - val_mae: 50201.6836
Epoch 55/100
250/250 [==============================] - 0s 2ms/step - loss: 49565.0156 - mae: 49565.0156 - val_loss: 50189.2969 - val_mae: 50189.2969
Epoch 56/100
250/250 [==============================] - 0s 2ms/step - loss: 49561.3125 - mae: 49561.3125 - val_loss: 50188.8086 - val_mae: 50188.8086
Epoch 57/100
250/250 [==============================] - 0s 2ms/step - loss: 49551.0195 - mae: 49551.0195 - val_loss: 50189.2930 - val_mae: 50189.2930
Epoch 58/100
250/250 [==============================] - 0s 2ms/step - loss: 49544.8477 - mae: 49544.8477 - val_loss: 50191.6758 - val_mae: 50191.6758
Epoch 59/100
250/250 [==============================] - 0s 2ms/step - loss: 49537.8984 - mae: 49537.8984 - val_loss: 50193.8008 - val_mae: 50193.8008
Epoch 60/100
250/250 [==============================] - 0s 2ms/step - loss: 49532.2617 - mae: 49532.2617 - val_loss: 50200.3086 - val_mae: 50200.3086
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 49525.3750 - mae: 49525.3750 - val_loss: 50183.6211 - val_mae: 50183.6211
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 49517.2070 - mae: 49517.2070 - val_loss: 50183.2031 - val_mae: 50183.2031
Epoch 63/100
250/250 [==============================] - 0s 2ms/step - loss: 49511.3086 - mae: 49511.3086 - val_loss: 50185.5391 - val_mae: 50185.5391
Epoch 64/100
250/250 [==============================] - 0s 2ms/step - loss: 49506.6445 - mae: 49506.6445 - val_loss: 50189.7812 - val_mae: 50189.7812
Epoch 65/100
250/250 [==============================] - 0s 2ms/step - loss: 49500.4102 - mae: 49500.4102 - val_loss: 50181.4766 - val_mae: 50181.4766
Epoch 66/100
250/250 [==============================] - 1s 2ms/step - loss: 49495.1797 - mae: 49495.1797 - val_loss: 50180.1641 - val_mae: 50180.1641
Epoch 67/100
250/250 [==============================] - 0s 2ms/step - loss: 49488.9727 - mae: 49488.9727 - val_loss: 50171.6758 - val_mae: 50171.6758
Epoch 68/100
250/250 [==============================] - 0s 2ms/step - loss: 49485.1992 - mae: 49485.1992 - val_loss: 50172.8125 - val_mae: 50172.8125
Epoch 69/100
250/250 [==============================] - 0s 2ms/step - loss: 49476.2148 - mae: 49476.2148 - val_loss: 50176.7852 - val_mae: 50176.7852
Epoch 70/100
250/250 [==============================] - 0s 2ms/step - loss: 49472.3359 - mae: 49472.3359 - val_loss: 50166.9102 - val_mae: 50166.9102
Epoch 71/100
250/250 [==============================] - 0s 2ms/step - loss: 49467.5352 - mae: 49467.5352 - val_loss: 50166.6680 - val_mae: 50166.6680
Epoch 72/100
250/250 [==============================] - 0s 2ms/step - loss: 49463.8438 - mae: 49463.8438 - val_loss: 50189.9414 - val_mae: 50189.9414
Epoch 73/100
250/250 [==============================] - 0s 2ms/step - loss: 49457.3594 - mae: 49457.3594 - val_loss: 50188.5742 - val_mae: 50188.5742
Epoch 74/100
250/250 [==============================] - 0s 2ms/step - loss: 49454.8438 - mae: 49454.8438 - val_loss: 50188.4883 - val_mae: 50188.4883
Epoch 75/100
250/250 [==============================] - 0s 2ms/step - loss: 49447.6484 - mae: 49447.6484 - val_loss: 50180.6602 - val_mae: 50180.6602
Epoch 76/100
250/250 [==============================] - 0s 2ms/step - loss: 49442.0156 - mae: 49442.0156 - val_loss: 50174.0234 - val_mae: 50174.0234
Epoch 77/100
250/250 [==============================] - 1s 2ms/step - loss: 49436.3828 - mae: 49436.3828 - val_loss: 50165.6914 - val_mae: 50165.6914
Epoch 78/100
250/250 [==============================] - 1s 3ms/step - loss: 49435.9648 - mae: 49435.9648 - val_loss: 50181.9453 - val_mae: 50181.9453
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 49434.4023 - mae: 49434.4023 - val_loss: 50175.4727 - val_mae: 50175.4727
Epoch 80/100
250/250 [==============================] - 1s 2ms/step - loss: 49427.4766 - mae: 49427.4766 - val_loss: 50178.7070 - val_mae: 50178.7070
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 49420.1953 - mae: 49420.1953 - val_loss: 50173.1250 - val_mae: 50173.1250
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 49418.5469 - mae: 49418.5469 - val_loss: 50168.6211 - val_mae: 50168.6211
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 49416.3984 - mae: 49416.3984 - val_loss: 50168.6094 - val_mae: 50168.6094
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 49413.8867 - mae: 49413.8867 - val_loss: 50185.4453 - val_mae: 50185.4453
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 49407.4141 - mae: 49407.4141 - val_loss: 50174.0508 - val_mae: 50174.0508
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 49399.7344 - mae: 49399.7344 - val_loss: 50177.6602 - val_mae: 50177.6602
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 49398.8672 - mae: 49398.8672 - val_loss: 50170.2812 - val_mae: 50170.2812

In [19]:
# load tensorboard extension
%load_ext tensorboard

In [20]:
%tensorboard --logdir regressionlogs/fit --port 6008

Reusing TensorBoard on port 6008 (pid 24964), started 0:24:44 ago. (Use '!kill 24964' to kill it.)

In [21]:
#evaluate model on the test data
test_loss, test_mae=model.evaluate(X_test, y_test)
print(f'Test MAE: {test_mae}')

63/63 [==============================] - 0s 1ms/step - loss: 50165.6914 - mae: 50165.6914
Test MAE: 50165.69140625

In [22]:
train_loss, train_mae = model.evaluate(X_train, y_train)
print("Train MAE:", train_mae)

250/250 [==============================] - 0s 1ms/step - loss: 49419.4336 - mae: 49419.4336
Train MAE: 49419.43359375

In [24]:
model.save('regression_model.h5')

d:\conda_envs\DL1\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(